output_file: glue_column_metadata.csv
output_location: s3://athena-destination-store-cg/athena
bucket_name: athena-destination-store-cg
folder_path: vectorstore/
knowledge_layer_file: knowledge_layer.json
metadata_file: metadata/glue_column_metadata.csv
faiss_local_paths: ['vectorstore/prompt_embeddings.index.faiss']
pkl_local_paths: ['vectorstore/prompt_embeddings.index.pkl']
faiss_doc_paths: ['documents/document_store.faiss']
pkl_doc_paths: ['documents/document_store.pkl']
doc_store_path: documents/
json_file_path: authentication\users.json
