output_file: glue_column_metadata.csv
output_location: s3://athena-destination-store-cg/athena
bucket_name: athena-destination-store-cg
folder_path: D:/Git/Text2SQL/vectorstore/
knowledge_layer_file: knowledge_layer.json
metadata_file: D:\Git\Text2SQL\metadata\glue_column_metadata.csv
faiss_local_paths: ['D:/Git/Text2SQL/vectorstore/prompt_embeddings.index.faiss']
pkl_local_paths: ['D:/Git/Text2SQL/vectorstore/prompt_embeddings.index.pkl']
json_file_path: D:/Git/Text2SQL/authentication/users.json